import akselinlaskija from './icons/akselinlaskija.svg';
import opastin_jo from './icons/opastin_jo.svg';
import opastin_ysj from './icons/opastin_ysj.svg';
import ryhmityseristinNopea from './icons/ryhmityseristinNopea.svg';
import vaihde_rr from './icons/vaihde_rr.svg';
import vaihde_yrv_kokonaan from './icons/vaihde_yrv_kokonaan.svg';
import alikulku from './icons/alikulku.svg';
import opastin_jp from './icons/opastin_jp.svg';
import opastin_ysje from './icons/opastin_ysje.svg';
import sahkoistyspaattyy from './icons/sahkoistyspaattyy.svg';
import vaihde_skvo from './icons/vaihde_skvo.svg';
import vaihde_yrv_oikea from './icons/vaihde_yrv_oikea.svg';
import asemarakennus from './icons/asemarakennus.svg';
import opastin_me from './icons/opastin_me.svg';
import opastin_ysjv from './icons/opastin_ysjv.svg';
import seislevy from './icons/seislevy.svg';
import vaihde_skvo_keskinopea from './icons/vaihde_skvo_keskinopea.svg';
import vaihde_yrv_vasen from './icons/vaihde_yrv_vasen.svg';
import avainsalpalaite from './icons/avainsalpalaite.svg';
import opastin_pa from './icons/opastin_pa.svg';
import opastin_ysv from './icons/opastin_ysv.svg';
import tankkauspiste from './icons/tankkauspiste.svg';
import vaihde_skvo_kokonaan from './icons/vaihde_skvo_kokonaan.svg';
import vaihde_yvo from './icons/vaihde_yvo.svg';
import baliisi from './icons/baliisi.svg';
import opastin_pa2 from './icons/opastin_pa2.svg';
import opastin_ysve from './icons/opastin_ysve.svg';
import tasoristeyksen_varoituslaitos from './icons/tasoristeyksen_varoituslaitos.svg';
import vaihde_skvo_kokonaan_keskinopea from './icons/vaihde_skvo_kokonaan_keskinopea.svg';
import vaihde_yvo_keskinopea from './icons/vaihde_yvo_keskinopea.svg';
import baliisitoistopiste from './icons/baliisitoistopiste.svg';
import opastin_pav from './icons/opastin_pav.svg';
import opastin_yv from './icons/opastin_yv.svg';
import tasoristeys from './icons/tasoristeys.svg';
import vaihde_skvo_kokonaan_nopea from './icons/vaihde_skvo_kokonaan_nopea.svg';
import vaihde_yvo_kokonaan from './icons/vaihde_yvo_kokonaan.svg';
import erotusjakso from './icons/erotusjakso.svg';
import opastin_ps from './icons/opastin_ps.svg';
import paikantamismerkki_laskeva from './icons/paikantamismerkki_laskeva.svg';
import tunneli from './icons/tunneli.svg';
import vaihde_skvo_nopea from './icons/vaihde_skvo_nopea.svg';
import vaihde_yvo_kokonaan_keskinopea from './icons/vaihde_yvo_kokonaan_keskinopea.svg';
import erotuskentta from './icons/erotuskentta.svg';
import opastin_ps2 from './icons/opastin_ps2.svg';
import paikantamismerkki_nouseva from './icons/paikantamismerkki_nouseva.svg';
import tuulipussi from './icons/tuulipussi.svg';
import vaihde_skvv from './icons/vaihde_skvv.svg';
import vaihde_yvo_kokonaan_nopea from './icons/vaihde_yvo_kokonaan_nopea.svg';
import hissi from './icons/hissi.svg';
import opastin_ps2v from './icons/opastin_ps2v.svg';
import paineilma from './icons/paineilma.svg';
import tyonaikaineneristin from './icons/tyonaikaineneristin.svg';
import vaihde_skvv_keskinopea from './icons/vaihde_skvv_keskinopea.svg';
import vaihde_yvo_nopea from './icons/vaihde_yvo_nopea.svg';
import jatevesi from './icons/jatevesi.svg';
import opastin_psv from './icons/opastin_psv.svg';
import paloposti from './icons/paloposti.svg';
import vaihde_krv from './icons/vaihde_krv.svg';
import vaihde_skvv_kokonaan from './icons/vaihde_skvv_kokonaan.svg';
import vaihde_yvv from './icons/vaihde_yvv.svg';
import kilometrimerkki from './icons/kilometrimerkki.svg';
import opastin_ra from './icons/opastin_ra.svg';
import porrasnousu from './icons/porrasnousu.svg';
import vaihde_krv_kokonaan from './icons/vaihde_krv_kokonaan.svg';
import vaihde_skvv_kokonaan_keskinopea from './icons/vaihde_skvv_kokonaan_keskinopea.svg';
import vaihde_yvv_keskinopea from './icons/vaihde_yvv_keskinopea.svg';
import korkeuspiste from './icons/korkeuspiste-24.svg';
import opastin_rd from './icons/opastin_rd.svg';
import portti from './icons/portti.svg';
import vaihde_krv_oikea from './icons/vaihde_krv_oikea.svg';
import vaihde_skvv_kokonaan_nopea from './icons/vaihde_skvv_kokonaan_nopea.svg';
import vaihde_yvv_kokonaan from './icons/vaihde_yvv_kokonaan.svg';
import kuormauslaituri from './icons/kuormauslaituri.svg';
import opastin_rp from './icons/opastin_rp.svg';
import puolipuomi from './icons/puolipuomi.svg';
import vaihde_krv_vasen from './icons/vaihde_krv_vasen.svg';
import vaihde_skvv_nopea from './icons/vaihde_skvv_nopea.svg';
import vaihde_yvv_kokonaan_keskinopea from './icons/vaihde_yvv_kokonaan_keskinopea.svg';
import kuumakayntiilmaisin from './icons/kuumakayntiilmaisin.svg';
import opastin_sm from './icons/opastin_sm.svg';
import puomi from './icons/puomi.svg';
import vaihde_kvo from './icons/vaihde_kvo.svg';
import vaihde_srr from './icons/vaihde_srr.svg';
import vaihde_yvv_kokonaan_nopea from './icons/vaihde_yvv_kokonaan_nopea.svg';
import laitos from './icons/laitos.svg';
import opastin_su from './icons/opastin_su.svg';
import puskin from './icons/puskin.svg';
import vaihde_kvo_kokonaan from './icons/vaihde_kvo_kokonaan.svg';
import vaihde_tyv from './icons/vaihde_tyv.svg';
import vaihde_yvv_nopea from './icons/vaihde_yvv_nopea.svg';
import latauspiste from './icons/latauspiste.svg';
import opastin_to from './icons/opastin_to.svg';
import pyoravoimailmaisin from './icons/pyoravoimailmaisin.svg';
import vaihde_kvo_oikea from './icons/vaihde_kvo_oikea.svg';
import vaihde_tyv_kokonaan from './icons/vaihde_tyv_kokonaan.svg';
import vesi from './icons/vesi.svg';
import liikennepaikan_vaihtotyon_raja from './icons/liikennepaikan_vaihtotyon_raja.svg';
import opastin_vk from './icons/opastin_vk.svg';
import raideeristys from './icons/raideeristys.svg';
import vaihde_kvo_vasen from './icons/vaihde_kvo_vasen.svg';
import vaihde_ukvo from './icons/vaihde_ukvo.svg';
import virroitinvalvontakamera from './icons/virroitinvalvontakamera.svg';
import liikennepaikanraja from './icons/liikennepaikanraja.svg';
import opastin_y4 from './icons/opastin_y4.svg';
import raiteensulku from './icons/raiteensulku.svg';
import vaihde_kvv from './icons/vaihde_kvv.svg';
import vaihde_ukvo_kokonaan from './icons/vaihde_ukvo_kokonaan.svg';
import ylikulku from './icons/ylikulku.svg';
import liikenteenohjauksenraja from './icons/liikenteenohjauksenraja.svg';
import opastin_ye from './icons/opastin_ye.svg';
import raiteensulkuKasin from './icons/raiteensulkuKasin.svg';
import vaihde_kvv_kokonaan from './icons/vaihde_kvv_kokonaan.svg';
import vaihde_ukvv from './icons/vaihde_ukvv.svg';
import maadoitin from './icons/maadoitin.svg';
import opastin_ys from './icons/opastin_ys.svg';
import rfidlukija from './icons/rfidlukija.svg';
import vaihde_kvv_oikea from './icons/vaihde_kvv_oikea.svg';
import vaihde_ukvv_kokonaan from './icons/vaihde_ukvv_kokonaan.svg';
import opastin_es from './icons/opastin_es.svg';
import opastin_yse from './icons/opastin_yse.svg';
import ryhmityseristin from './icons/ryhmityseristin.svg';
import vaihde_kvv_vasen from './icons/vaihde_kvv_vasen.svg';
import vaihde_yrv from './icons/vaihde_yrv.svg';


module.exports = (function() {
  window['icons/akselinlaskija'] = akselinlaskija;
  window['icons/opastin_jo'] = opastin_jo;
  window['icons/opastin_ysj'] = opastin_ysj;
  window['icons/ryhmityseristinNopea'] = ryhmityseristinNopea;
  window['icons/vaihde_rr'] = vaihde_rr;
  window['icons/vaihde_yrv_kokonaan'] = vaihde_yrv_kokonaan;
  window['icons/alikulku'] = alikulku;
  window['icons/opastin_jp'] = opastin_jp;
  window['icons/opastin_ysje'] = opastin_ysje;
  window['icons/sahkoistyspaattyy'] = sahkoistyspaattyy;
  window['icons/vaihde_skvo'] = vaihde_skvo;
  window['icons/vaihde_yrv_oikea'] = vaihde_yrv_oikea;
  window['icons/asemarakennus'] = asemarakennus;
  window['icons/opastin_me'] = opastin_me;
  window['icons/opastin_ysjv'] = opastin_ysjv;
  window['icons/seislevy'] = seislevy;
  window['icons/vaihde_skvo_keskinopea'] = vaihde_skvo_keskinopea;
  window['icons/vaihde_yrv_vasen'] = vaihde_yrv_vasen;
  window['icons/avainsalpalaite'] = avainsalpalaite;
  window['icons/opastin_pa'] = opastin_pa;
  window['icons/opastin_ysv'] = opastin_ysv;
  window['icons/tankkauspiste'] = tankkauspiste;
  window['icons/vaihde_skvo_kokonaan'] = vaihde_skvo_kokonaan;
  window['icons/vaihde_yvo'] = vaihde_yvo;
  window['icons/baliisi'] = baliisi;
  window['icons/opastin_pa2'] = opastin_pa2;
  window['icons/opastin_ysve'] = opastin_ysve;
  window['icons/tasoristeyksen_varoituslaitos'] = tasoristeyksen_varoituslaitos;
  window['icons/vaihde_skvo_kokonaan_keskinopea'] = vaihde_skvo_kokonaan_keskinopea;
  window['icons/vaihde_yvo_keskinopea'] = vaihde_yvo_keskinopea;
  window['icons/baliisitoistopiste'] = baliisitoistopiste;
  window['icons/opastin_pav'] = opastin_pav;
  window['icons/opastin_yv'] = opastin_yv;
  window['icons/tasoristeys'] = tasoristeys;
  window['icons/vaihde_skvo_kokonaan_nopea'] = vaihde_skvo_kokonaan_nopea;
  window['icons/vaihde_yvo_kokonaan'] = vaihde_yvo_kokonaan;
  window['icons/erotusjakso'] = erotusjakso;
  window['icons/opastin_ps'] = opastin_ps;
  window['icons/paikantamismerkki_laskeva'] = paikantamismerkki_laskeva;
  window['icons/tunneli'] = tunneli;
  window['icons/vaihde_skvo_nopea'] = vaihde_skvo_nopea;
  window['icons/vaihde_yvo_kokonaan_keskinopea'] = vaihde_yvo_kokonaan_keskinopea;
  window['icons/erotuskentta'] = erotuskentta;
  window['icons/opastin_ps2'] = opastin_ps2;
  window['icons/paikantamismerkki_nouseva'] = paikantamismerkki_nouseva;
  window['icons/tuulipussi'] = tuulipussi;
  window['icons/vaihde_skvv'] = vaihde_skvv;
  window['icons/vaihde_yvo_kokonaan_nopea'] = vaihde_yvo_kokonaan_nopea;
  window['icons/hissi'] = hissi;
  window['icons/opastin_ps2v'] = opastin_ps2v;
  window['icons/paineilma'] = paineilma;
  window['icons/tyonaikaineneristin'] = tyonaikaineneristin;
  window['icons/vaihde_skvv_keskinopea'] = vaihde_skvv_keskinopea;
  window['icons/vaihde_yvo_nopea'] = vaihde_yvo_nopea;
  window['icons/jatevesi'] = jatevesi;
  window['icons/opastin_psv'] = opastin_psv;
  window['icons/paloposti'] = paloposti;
  window['icons/vaihde_krv'] = vaihde_krv;
  window['icons/vaihde_skvv_kokonaan'] = vaihde_skvv_kokonaan;
  window['icons/vaihde_yvv'] = vaihde_yvv;
  window['icons/kilometrimerkki'] = kilometrimerkki;
  window['icons/opastin_ra'] = opastin_ra;
  window['icons/porrasnousu'] = porrasnousu;
  window['icons/vaihde_krv_kokonaan'] = vaihde_krv_kokonaan;
  window['icons/vaihde_skvv_kokonaan_keskinopea'] = vaihde_skvv_kokonaan_keskinopea;
  window['icons/vaihde_yvv_keskinopea'] = vaihde_yvv_keskinopea;
  window['icons/korkeuspiste-24'] = korkeuspiste-24;
  window['icons/opastin_rd'] = opastin_rd;
  window['icons/portti'] = portti;
  window['icons/vaihde_krv_oikea'] = vaihde_krv_oikea;
  window['icons/vaihde_skvv_kokonaan_nopea'] = vaihde_skvv_kokonaan_nopea;
  window['icons/vaihde_yvv_kokonaan'] = vaihde_yvv_kokonaan;
  window['icons/kuormauslaituri'] = kuormauslaituri;
  window['icons/opastin_rp'] = opastin_rp;
  window['icons/puolipuomi'] = puolipuomi;
  window['icons/vaihde_krv_vasen'] = vaihde_krv_vasen;
  window['icons/vaihde_skvv_nopea'] = vaihde_skvv_nopea;
  window['icons/vaihde_yvv_kokonaan_keskinopea'] = vaihde_yvv_kokonaan_keskinopea;
  window['icons/kuumakayntiilmaisin'] = kuumakayntiilmaisin;
  window['icons/opastin_sm'] = opastin_sm;
  window['icons/puomi'] = puomi;
  window['icons/vaihde_kvo'] = vaihde_kvo;
  window['icons/vaihde_srr'] = vaihde_srr;
  window['icons/vaihde_yvv_kokonaan_nopea'] = vaihde_yvv_kokonaan_nopea;
  window['icons/laitos'] = laitos;
  window['icons/opastin_su'] = opastin_su;
  window['icons/puskin'] = puskin;
  window['icons/vaihde_kvo_kokonaan'] = vaihde_kvo_kokonaan;
  window['icons/vaihde_tyv'] = vaihde_tyv;
  window['icons/vaihde_yvv_nopea'] = vaihde_yvv_nopea;
  window['icons/latauspiste'] = latauspiste;
  window['icons/opastin_to'] = opastin_to;
  window['icons/pyoravoimailmaisin'] = pyoravoimailmaisin;
  window['icons/vaihde_kvo_oikea'] = vaihde_kvo_oikea;
  window['icons/vaihde_tyv_kokonaan'] = vaihde_tyv_kokonaan;
  window['icons/vesi'] = vesi;
  window['icons/liikennepaikan_vaihtotyon_raja'] = liikennepaikan_vaihtotyon_raja;
  window['icons/opastin_vk'] = opastin_vk;
  window['icons/raideeristys'] = raideeristys;
  window['icons/vaihde_kvo_vasen'] = vaihde_kvo_vasen;
  window['icons/vaihde_ukvo'] = vaihde_ukvo;
  window['icons/virroitinvalvontakamera'] = virroitinvalvontakamera;
  window['icons/liikennepaikanraja'] = liikennepaikanraja;
  window['icons/opastin_y4'] = opastin_y4;
  window['icons/raiteensulku'] = raiteensulku;
  window['icons/vaihde_kvv'] = vaihde_kvv;
  window['icons/vaihde_ukvo_kokonaan'] = vaihde_ukvo_kokonaan;
  window['icons/ylikulku'] = ylikulku;
  window['icons/liikenteenohjauksenraja'] = liikenteenohjauksenraja;
  window['icons/opastin_ye'] = opastin_ye;
  window['icons/raiteensulkuKasin'] = raiteensulkuKasin;
  window['icons/vaihde_kvv_kokonaan'] = vaihde_kvv_kokonaan;
  window['icons/vaihde_ukvv'] = vaihde_ukvv;
  window['icons/maadoitin'] = maadoitin;
  window['icons/opastin_ys'] = opastin_ys;
  window['icons/rfidlukija'] = rfidlukija;
  window['icons/vaihde_kvv_oikea'] = vaihde_kvv_oikea;
  window['icons/vaihde_ukvv_kokonaan'] = vaihde_ukvv_kokonaan;
  window['icons/opastin_es'] = opastin_es;
  window['icons/opastin_yse'] = opastin_yse;
  window['icons/ryhmityseristin'] = ryhmityseristin;
  window['icons/vaihde_kvv_vasen'] = vaihde_kvv_vasen;
  window['icons/vaihde_yrv'] = vaihde_yrv;
})();
